windup/windup-distribution

pom.xml, src/main/resources/bash-completion/windup
Related PR: https://github.com/windup/windup/pull/596
=> Switching bootstrap to no longer depend on the shell

src/main/assembly/assembly-offline.xml, src/main/resources/bin/windup, src/main/resources/bin/windup.bat, src/main/resources/windup-version.txt
NOTE: If you are able to test the various scenarios on windows, that would be great. I think the common cases are less likely to break, but my test environment is really really slow and I'm sure that I didn't test everything there.
=> WINDUP-711: Smarter inferencing of variables

pom.xml, src/main/assembly/assembly-offline.xml
Related to https://github.com/windup/windup/pull/774
=> WINDUP-846: Windup bootstrap runs slow even for showing help usage

src/main/resources/README.txt
=> WINDUP-844 - Adding information to README.txt for end users of offline

src/main/resources/bin/windup, src/main/resources/bin/windup.bat
https://issues.jboss.org/browse/WINDUP-845
=> WINDUP-845 check java version and set appropriately MaxPermSize or MaxMetaspaceSize

src/main/resources/bin/windup
Another try at https://github.com/windup/windup-distribution/pull/33
Hopefully gets the quoting right?
=> Switch to exec and less quirky quoting

src/main/resources/bin/windup
=> Switched to bash

pom.xml
continuation of https://github.com/windup/windup/pull/1084 for passing for https://github.com/windup/windup-web/pull/272
=> Upgraded Forge to 3.6.0.Final and Furnace 2.25.3.Final

pom.xml
https://issues.jboss.org/browse/WINDUP-1328
=> WINDUP-1328 - update of furnace to 2.25.4.Final

src/main/resources/logging.properties
Asynchronous handler attached to `FILE` handler with `DISCARD` mode enabled.
=> WINDUP-1551 Logging: switch to asynchronous and drop mode

src/main/resources/ignore/proprietary.package-ignore.txt
https://issues.jboss.org/browse/WINDUP-1622
the other way to https://github.com/windup/windup-rulesets/pull/259 how to block java mail API for scanning
=> WINDUP-1622: adding Mail APIs to blacklist

src/main/resources/ignore/blacklist-libraries.package-ignore.txt, src/main/resources/ignore/proprietary.package-ignore.txt
https://issues.jboss.org/browse/WINDUP-1624
one of possible solution to blacklist all known libraries from polution of occurences
I created additional ignore file and move here also Mail API packages from WINDUP-1622
=> WINDUP-1624: adding more blacklisted packages of known libraries

src/main/resources/bin/rhamt-cli
https://issues.jboss.org/browse/WINDUP-1557
=> WINDUP-1557: Fix for ulimit issue

src/main/resources/JBossEULA.txt
https://issues.jboss.org/browse/WINDUP-1905
=> WINDUP-1905: Add the missing JBoss EULA file

pom.xml, src/main/resources/bin/rhamt-cli, src/main/resources/bin/rhamt-cli.bat
Depends on https://github.com/windup/windup/pull/1332 and https://github.com/windup/windup-rulesets/pull/349
Follows https://github.com/windup/windup-distribution/pull/54 thanks @jsight
=> WINDUP-2171 JDK 11 compatibility - CLI

LICENSE
https://issues.jboss.org/browse/WINDUP-2370
=> WINDUP-2370 Create LICENSE

src/main/resources/labels/README.txt
https://issues.jboss.org/browse/WINDUP-2332
This PR just adds the `labels` folder so the user can add custom files to that folder in order to tests his custom Target Runtime xml files.
=> Windup 2332 - Application List Filtering/Labelling to support Target Runtime Selection

pom.xml
https://issues.redhat.com/browse/WINDUP-2510
=> WINDUP-2510 Bump Furnace version to 2.28.4.Final

pom.xml
https://issues.redhat.com/browse/WINDUP-2667
=> WINDUP-2667 version upgrade

src/main/resources/bin/mta-cli
https://issues.redhat.com/browse/WINDUP-2620
=> WINDUP-2620 set ulimit to 5000

src/main/resources/bin/mta-cli
https://issues.redhat.com/browse/WINDUP-2620
=> WINDUP-2620-reset-value-to-ulimit

src/main/resources/bin/mta-cli
https://issues.redhat.com/browse/WINDUP-2705
=> WINDUP-2705 Changed requested limit

src/main/resources/bin/mta-cli
https://issues.redhat.com/browse/WINDUP-2705
Backport of #68
=> WINDUP-2705 Changed requested limit (#68)

pom.xml
https://issues.redhat.com/browse/WINDUP-2789
=> WINDUP-2789: change pom version for new release

pom.xml, src/main/assembly/assembly-no-index.xml
https://issues.redhat.com/browse/WINDUP-3178
=> WINDUP-3178 Creating a CLI without Maven Lucene index

pom.xml
Once https://github.com/windup/windup/pull/1427 will be merged, this can be merged as well.
As long as https://github.com/windup/windup/pull/1427 is open, this can **NOT** be merged and hence it has the `Work in Progress` label.
=> Enable Diva addon

pom.xml
Once https://github.com/windup/windup/pull/1501 will be merged, this can be merged as well.
=> Bump versions to Furnace 2.29.1.Final, Forge 3.9.8.Final

.github/workflows/pull_request_push_build.yml, build/settings.xml, pom.xml
Build Windup CLI using:
- custom `settings.xml` file
- latest snapshot version for Windup dependencies
- multiple JDK distributions (adopt and temurin)
- mutiple OS (Ubuntu, Windows, MacOS)
=> Added Github workflow with job for building PRs and pushes

src/main/resources/bin/mta-cli, src/main/resources/bin/mta-cli.bat
https://issues.redhat.com/browse/WINDUP-3362
=> WINDUP-3362: update openrewrite rewrite-maven-plugin version

pom.xml
Refers to https://github.com/windup/windup/pull/1504
=> Bump Forge 3.10.0.Final

pom.xml
This is needed to be merged with https://github.com/windup/windup/pull/1508
=> include windup-rules-yaml addon

.github/workflows/pull_request_push_build.yml, pom.xml
https://issues.redhat.com/browse/WINDUP-3681
=> [WINDUP-3681] - Upgrade maven-assembly-plugin version

.github/workflows/pull_request_push_build.yml
backport #106  #110 
closes #108 #105
=> Enabled GH Jobs for 'release' branches + Fix Maven version to '3.8.7' 

pom.xml
BasePR https://github.com/windup/windup-distribution/pull/103
https://issues.redhat.com/browse/WINDUP-3681
=> [releases/6.1.z][WINDUP-3681] - Upgrade maven-assembly-plugin version

.github/workflows/pull_request_push_build.yml
=> [releases/6.1.z] Standalone workflows

src/main/resources/bin/windup-cli.bat
See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3973).
=> [WINDUP-3973] Fix windup-cli.bat file - Windup initialisation
